exports.NotificationType = {
  EVENT_MOTION_DETECTED: 3101,
  EVENT_SOMEONE_SPOTTED: 3102,
  EVENT_DOORBELL_PRESSED: 3103,
  EVENT_CRYING_DETECTED: 3104,
  EVENT_SOUND_DETECTED: 3105,
  EVENT_PET_DETECTED: 3106,
}

exports.NotificationTypeByString = {
  EVENT_MOTION_DETECTED: 'Motion is detected',
  EVENT_SOMEONE_SPOTTED: 'Someone has been spotted'
}